//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpClockTbl
    {
        public int EmpClkID { get; set; }
        public int EmpId { get; set; }
        public System.DateTime EmpWokDate { get; set; }
        public string EmpWokDay { get; set; }
        public string EmpWorkStartTime { get; set; }
        public string EmpWorkFinishTime { get; set; }
        public string EmpWorkHours { get; set; }
        public string EmpClkDescription { get; set; }
    
        public virtual EmployeeTbl EmployeeTbl { get; set; }
    }
}
