//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeTbl()
        {
            this.EmpClockTbls = new HashSet<EmpClockTbl>();
            this.EmpPayTbls = new HashSet<EmpPayTbl>();
        }
    
        public int EmpId { get; set; }
        public string EmpType { get; set; }
        public string EmpName { get; set; }
        public string EmpSurname { get; set; }
        public string EmpUsername { get; set; }
        public string EmpPassword { get; set; }
        public decimal EmpMNumber { get; set; }
        public string EmpEmail { get; set; }
        public string EmpGender { get; set; }
        public string EmpBankName { get; set; }
        public decimal EmpBankAccountNO { get; set; }
        public int EmpPayRate { get; set; }
        public System.DateTime EmpAddDate { get; set; }
        public int DeptId { get; set; }
        public string EmpAddress { get; set; }
        public Nullable<decimal> EmpIRD { get; set; }
        public string EmpStatus { get; set; }
    
        public virtual DepartmentTbl DepartmentTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpClockTbl> EmpClockTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpPayTbl> EmpPayTbls { get; set; }
    }
}
