//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPayTbl
    {
        public int EmpPayID { get; set; }
        public System.DateTime EmpSalaryDate { get; set; }
        public decimal EmpTotalHours { get; set; }
        public decimal EmpTotalPay { get; set; }
        public decimal EmpTaxPay { get; set; }
        public decimal EmpCreditPay { get; set; }
        public int EmpId { get; set; }
    
        public virtual EmployeeTbl EmployeeTbl { get; set; }
    }
}
